-- Script para criar as tabelas ApiSpecs e VersionAssociations no Oracle
-- Execute este script no seu banco Oracle antes de rodar a aplicação

-- Tabela para armazenar as especificações de API (YAML)
CREATE TABLE kmm.api_specs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    yaml CLOB NOT NULL
);

-- Tabela para associações entre versões e endpoints
CREATE TABLE kmm.version_associations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    cod_modulo VARCHAR2(50) NOT NULL,
    api_spec_id NUMBER NOT NULL,
    endpoint_path VARCHAR2(500) NOT NULL,
    endpoint_method VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_version_assoc_client_module 
        FOREIGN KEY (cliente_id, cod_modulo) 
        REFERENCES kmm.v$cliente_modulo_versao(cliente_id, cod_modulo),
    CONSTRAINT fk_version_assoc_api_spec 
        FOREIGN KEY (api_spec_id) 
        REFERENCES kmm.api_specs(id) ON DELETE CASCADE
);

-- Índices para melhor performance
CREATE INDEX idx_version_assoc_client_module ON kmm.version_associations(cliente_id, cod_modulo);
CREATE INDEX idx_version_assoc_api_spec ON kmm.version_associations(api_spec_id);
CREATE INDEX idx_api_specs_name ON kmm.api_specs(name);

-- Comentários nas tabelas
COMMENT ON TABLE kmm.api_specs IS 'Armazena especificações OpenAPI em formato YAML';
COMMENT ON TABLE kmm.version_associations IS 'Associa endpoints específicos a versões de módulos por cliente';
